name: Build and Push Docker Image

on:
  push:
    branches:
      - gitmotion/main    # You can also specify the branch where you want the action to trigger, like `develop`, or your custom branch.

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build the app
        run: pnpm build

  build:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (to support multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/it-tools:latest
          # Optionally add version tags or specific branch tags like:
          # tags: |
          #   ghcr.io/${{ secrets.GHCR_USERNAME }}/your-repo-name:latest
          #   ghcr.io/${{ secrets.GHCR_USERNAME }}/your-repo-name:${{ github.sha }}

      # Optionally log out
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
